site_name: LoopDocs
theme: flatly
google_analytics: ['UA-109876065-1', 'loopkit.github.io']
extra_css:
    - css/admonitions.css
markdown_extensions:
    - admonition
    - toc:
        permalink: ‚åÅ

pages:
- Home: 'index.md'
- FAQs:
    - 'Using This Site FAQs': 'faqs/docs-faqs.md'
    - 'General Loop FAQs': 'faqs/FAQs.md'
    - 'Omnipod FAQs': 'faqs/omnipod-faqs.md'
    - 'RileyLink FAQs': 'faqs/rileylink-faqs.md'
    - 'Algorithm FAQs': 'faqs/algorithm-faqs.md'
    - 'CGM FAQs': 'faqs/cgm-faqs.md'
    - 'Safety Tips': 'faqs/safety-faqs.md'
    - 'Glossary': 'faqs/glossary.md'
- Gear:
    - 'Insulin Pump':
        - 'Medtronic': 'setup/requirements/mdt-pump.md'
        - 'Omnipod': 'setup/requirements/omnipod-pump.md'
    - 'CGM': 'setup/requirements/cgm.md'
    - 'RileyLink': 'setup/requirements/rileylink.md'
    - 'Computer': 'setup/requirements/computer.md'
    - 'iPhone': 'setup/requirements/iphone.md'
    - 'Apple Developer': 'setup/requirements/appledev.md'
- Build App:
    - Overview: 'build/overview.md'
    - Prep Computer: 'build/build-computer.md'
    - Get Developer Account: 'build/build-developer.md'
    - Install Xcode: 'build/build-xcode.md'
    - Build Loop: 'build/build-loop.md'
    - Build Errors: 'build/build_errors.md'
    - Health Permissions: 'build/health.md'
    - Loop Study: 'build/jaeb-study.md'
    - Code Customization: 'build/code_customization.md'
    - New iPhone: 'build/new-iphone.md'
    - Update Loop: 'build/update/updating.md'
    - New Version Info: 'build/update/new-version.md'
- Set up App:
    - 'Overview': 'operation/overview.md'
    - 'Add Pump':
        - 'Add Medtronic': 'operation/loop-settings/mdt-pump.md'
        - 'Add Omnipod': 'operation/loop-settings/omnipod-pump.md'
    - 'Add CGM': 'operation/loop-settings/cgm.md'
    - 'Configurations': 'operation/loop-settings/configurations.md'
    - 'Loop Services': 'operation/loop-settings/services.md'
    - 'Loop Displays': 'operation/loop-settings/displays.md'
    - 'RileyLink menu': 'operation/loop-settings/rileylink.md'
- Operate:
    - How to Use Loop App:
        - 'Carb Entries': 'operation/features/carbs.md'
        - 'Bolus': 'operation/features/bolus.md'
        - 'Workout Targets': 'operation/features/workout.md'
        - 'Using ICE info': 'operation/features/ice.md'
        - 'Apple Watch': 'operation/features/watch.md'
        - 'iPhone widget': 'operation/features/widget.md'
        - 'Loop Notifications': 'operation/features/notifications.md'
        - 'Pump Battery': 'operation/features/battery.md'
    - 'Looping Tips':
        - 'Open Loop': 'operation/loop/open-loop.md'
        - 'Closed Loop': 'operation/loop/close-loop.md'
        - 'Loop Tips': 'operation/loop/looptips.md'
    - Algorithm:
        - 'Overview': 'operation/algorithm/overview.md'
        - 'Bolus Recommendations': 'operation/algorithm/bolus.md'
        - 'Glucose Prediction': 'operation/algorithm/prediction.md'
        - 'Temp Basal Adjustments': 'operation/algorithm/temp-basal.md'
    - Troubleshoot:
        - 'Overview': 'troubleshooting/overview.md'
        - 'Grey Loop': 'troubleshooting/green-loop.md'
        - 'Yellow/Red Loop': 'troubleshooting/yellow-red-loop.md'
        - 'Pod Pairing Failures': 'troubleshooting/pod-pairing.md'
        - 'MDT Priming and Sites': 'troubleshooting/priming.md'
        - 'Time Changes': 'troubleshooting/time-change.md'
        - 'MDT Pump Errors': 'troubleshooting/pump-errors.md'
        - 'Omnipod Faults': 'troubleshooting/omnipod-faults.md'
- Nightscout:
    - 'Overview': 'nightscout/overview.md'
    - 'Brand New NS': 'nightscout/new_user.md'
    - 'Retrofit Existing NS': 'nightscout/update_user.md'
    - 'NS Stopped Working': 'nightscout/mlab_cleanup.md'
    - 'Azure to Heroku': 'nightscout/azure_migration.md'
    - 'IFTTT': 'nightscout/ifttt.md'
    - 'Pebble': 'nightscout/pebble.md'
    - 'Remote Notifications': 'nightscout/pushover.md'
    - 'Reports': 'nightscout/reports.md'
