# yaml-language-server: $schema=https://squidfunk.github.io/mkdocs-material/schema.json
site_name: LoopDocs (DRAFT for 3.4)

theme:
    name: material
    language: en
    features:
        - navigation.footer
        - navigation.tabs
        - navigation.tabs.sticky
        - navigation.tracking
        - navigation.top
        - search.suggest
        - search.highlight
        - content.code.annotate
        - content.tooltips
    logo: loop-logo.png
    favicon: loop-logo.png
    palette:
        # Palette toggle for light mode
        - media: "(prefers-color-scheme: light)"
          scheme: default
          primary: custom
          toggle:
            icon: material/brightness-7
            name: Switch to dark mode

        # Palette toggle for dark mode
        - media: "(prefers-color-scheme: dark)"
          scheme: slate
          primary: custom
          toggle:
            icon: material/brightness-4
            name: Switch to light mode

# repo_url: https://github.com/LoopKit/Loop

extra_css:
    - stylesheets/extra.css
    - stylesheets/primary-color.css

markdown_extensions:
    - meta
    - abbr
    - admonition
    - attr_list
    - pymdownx.arithmatex:
          generic: true
    - pymdownx.details
    - pymdownx.emoji:
        emoji_index: !!python/name:materialx.emoji.twemoji 
        emoji_generator: !!python/name:materialx.emoji.to_svg
    - pymdownx.highlight
    - pymdownx.mark
    - pymdownx.tilde
    - pymdownx.inlinehilite
    - pymdownx.keys
    - pymdownx.superfences:
        # make exceptions to highlighting of code:
        custom_fences:
          - name:  mermaid
            class: mermaid
            format: !!python/name:pymdownx.superfences.fence_code_format
    - pymdownx.snippets:
        auto_append:
            - includes/tooltip-list.txt
    - toc:
        permalink: true
        permalink_title: Anchor link to this Header on this Page
        toc_depth: 3
        title: Headers on this Page
extra_javascript:
    - https://polyfill.io/v3/polyfill.min.js?features=es6
    - https://cdn.jsdelivr.net/npm/mathjax@3/es5/tex-mml-chtml.js

plugins:
    - search
    - htmlproofer:
        enabled: !ENV [CHECK_BROKEN_LINKS, False]
        raise_error_after_finish: true
    - redirects:
        redirect_maps:
            'build/build_errors.md': 'build/build-errors.md'
            'build/code_customization.md': 'build/code-customization.md'
            'build/step1.md': 'build/computer.md'
            'build/step10.md': 'build/test-settings.md'
            'build/step11.md': 'build/loop-data.md'
            'build/step12.md': 'build/community.md'
            'build/step14.md': 'build/build-app.md'
            'build/step2.md': 'build/phone.md'
            'build/step3.md': 'build/pump.md'
            'build/step4.md': 'build/cgm.md'
            'build/step5.md': 'build/rileylink.md'
            'build/step6.md': 'build/apple-developer.md'
            'build/step8.md': 'build/xcode-version.md'
            'build/step9.md': 'build/xcode-settings.md'
            'loop-3/displays_v3.md': 'loop-3/displays-v3.md'
            'nightscout/new_user.md': 'nightscout/new-user.md'
            'nightscout/ns_crossref.md': 'nightscout/ns-crossref.md'
            'nightscout/remote-overrides.md': 'nightscout/remote-overview.md'
            'nightscout/troublehoot.md': 'nightscout/troubleshoot.md'
            'nightscout/update_user.md': 'nightscout/update-user.md'
            'operation/features/workout.md': 'operation/features/overrides.md'
            'operation/loop-settings/services_v2.md': 'operation/loop-settings/services-v2.md'
            'troubleshooting/time-change.md': 'faqs/time-faqs.md'
            'troubleshooting/yellow-red-loop.md': 'troubleshooting/red-loop.md'
    - unused_files:
        enabled: !ENV [CHECK_UNUSED_FILES, False]
        excluded_files:
            - .DS_Store
            - build/.DS_Store            
            - gh-actions/.DS_Store
            - gh-actions/img/.DS_Store
            - loop-logo.png
            - stylesheets/extra.css
            - stylesheets/primary-color.css

use_directory_urls: !ENV [CHECK_BROKEN_LINKS, True]

nav:
- Home: 'index.md'
- Intro:
    - 'LoopDocs Overview': 'intro/overview-intro.md'
    - 'LoopDocs How-to': 'intro/loopdocs-how-to.md'
    - 'Requirements': 'intro/requirements.md'
    - 'Compatible iPhone': 'build/phone.md'
    - 'Compatible Pump': 'build/pump.md'
    - 'Compatible CGM': 'build/cgm.md'
    - 'RileyLink': 'build/rileylink.md'
    - 'Apple Developer Program': 'build/apple-developer.md'
    - 'Test Settings': 'build/test-settings.md'
    - 'Loop Data': 'build/loop-data.md'
    - 'Meet the Community': 'build/community.md'
- Build with Browser:
    - 'Build with Browser Overview': gh-actions/gh-overview.md
    - 'Configure to use Browser': gh-actions/gh-first-time.md
    - 'Install on Phone': gh-actions/gh-deploy.md
    - 'Update with Browser': gh-actions/gh-update.md
    - 'Errors with Browser': gh-actions/gh-errors.md
    - 'Build Other Apps with Browser': gh-actions/gh-other-apps.md
- Mac-Xcode Build:
    - 'Mac-Xcode Build Overview': 'build/overview.md'
    - 'Compatible Computer': 'build/computer.md'
    - 'Xcode Version': 'build/xcode-version.md'
    - 'Xcode Preferences': 'build/xcode-settings.md'
    - 'Build Loop': 'build/build-app.md'
    - 'Oh dear! Build errors?': 'build/build-errors.md'
    - 'Updating/Rebuilding': 'build/updating.md'
    - 'Build Free Loop': 'build/build-free-loop.md'
    - 'TestFlight from Xcode': 'build/testflight-xcode.md'
- Set Up:
    - 'Overview': 'loop-3/loop-3-overview.md'
    - 'Onboarding': 'loop-3/onboarding.md'
    - 'Add CGM': 'loop-3/add-cgm.md'
    - 'Add Pump': 'loop-3/add-pump.md'
    - 'Settings': loop-3/settings.md
    - 'Therapy Settings': 'loop-3/therapy-settings.md'
    - 'Optional: Services': 'loop-3/services.md'
    - 'Displays': 'loop-3/displays-v3.md'
    - 'RileyLink Display': 'operation/loop-settings/rileylink.md'
    - 'Omnipod Pump': loop-3/omnipod.md
    - 'Medtronic Pump': loop-3/medtronic.md
    - 'Features': 'loop-3/features.md'
    - 'Loop 2: Set Up App':
        - 'Loop 2 Overview': 'operation/overview.md'
        - 'Loop 2 Health Permissions': 'build/health.md'
        - 'Loop 2 Add Pump':
            - 'Loop 2 Add Medtronic': 'operation/loop-settings/mdt-pump.md'
            - 'Loop 2 Add Omnipod': 'operation/loop-settings/omnipod-pump.md'
        - 'Loop 2 Add CGM': 'operation/loop-settings/cgm.md'
        - 'Loop 2 Configuration': 'operation/loop-settings/configurations.md'
        - 'Loop 2 Services': 'operation/loop-settings/services-v2.md'
        - 'Loop 2 Displays': 'operation/loop-settings/displays.md'
        - 'Loop 2 Pump Settings': 'operation/loop-settings/pump-commands.md'
- Operate:
    - 'Open Loop': 'operation/loop/open-loop.md'
    - 'Closed Loop': 'operation/loop/close-loop.md'
    - 'Meal Entries': 'operation/features/carbs.md'
    - 'Bolus': 'operation/features/bolus.md'
    - 'Overrides': 'operation/features/overrides.md'
    - 'Apple Watch': 'operation/features/watch.md'
    - 'Loop Notifications': 'operation/features/notifications.md'
    - 'Pre-Meal Target': 'operation/features/premeal.md'
    - 'Meal Review': 'operation/features/ice.md'
    - 'iPhone Widget': 'operation/features/widget.md'
    - Loop Tips: 'operation/loop/looptips.md'
    - Algorithm:
        - 'Algorithm Overview': 'operation/algorithm/overview.md'
        - 'Bolus Recommendations': 'operation/algorithm/bolus.md'
        - 'Glucose Prediction': 'operation/algorithm/prediction.md'
        - 'Automated Adjustments': 'operation/algorithm/temp-basal.md'
- Troubleshoot:
    - 'Troubleshooting Overview': 'troubleshooting/overview.md'
    - 'Loop App Crashes': 'troubleshooting/loop-crashing.md'
    - 'Red Loop': 'troubleshooting/red-loop.md'
    - 'Pod Pairing Failures': 'troubleshooting/pod-pairing.md'
    - 'Omnipod Faults': 'troubleshooting/omnipod-faults.md'
    - 'MDT Pump Errors': 'troubleshooting/pump-errors.md'
    - 'MDT Pump Battery': 'operation/features/battery.md'
- 'Version':
    - 'Version Overview': 'version/overview-version.md'
    - 'Loop Releases': 'version/releases.md'
    - 'Code Customization': 'build/code-customization.md'
    - 'Customize using Browser': 'gh-actions/gh-customize.md'
    - 'Simulator Build': 'version/simulator.md'
    - 'Loop Development': 'version/development.md'
    - 'Build Loop Dev': 'version/build-dev.md'
    - 'LoopWorkspace': 'version/loopworkspace.md'
- Nightscout:
    - 'Nightscout Overview': 'nightscout/overview.md'
    - 'New Nightscout': 'nightscout/new-user.md'
    - 'Nightscout with Loop': 'nightscout/update-user.md'
    - 'Nightscout Troubleshooting': 'nightscout/troubleshoot.md'
    - 'Nightscout Cross Ref': 'nightscout/ns-crossref.md'
    - 'Remote Overview': 'nightscout/remote-overview.md'
    - 'Remote Configuration': 'nightscout/remote-config.md'
    - 'Remote Commands': 'nightscout/remote-commands.md'
    - 'Remote Errors': 'nightscout/remote-errors.md'
    - 'Loop Caregiver': 'nightscout/loop-caregiver.md'
- FAQs:
    - 'FAQs Overview': 'faqs/overview-faqs.md'
    - 'Safety Tips': 'faqs/safety-faqs.md'
    - 'Loop FAQs': 'faqs/FAQs.md'
    - 'Time FAQs': 'faqs/time-faqs.md'
    - 'Omnipod FAQs': 'faqs/omnipod-faqs.md'
    - 'CGM FAQs': 'faqs/cgm-faqs.md'
    - 'Update/Rebuild Loop FAQs': 'faqs/update-faqs.md'
    - 'New Phone Tips': 'faqs/new-phone.md'
    - 'RileyLink FAQs': 'faqs/rileylink-faqs.md'
    - 'Algorithm FAQs': 'faqs/algorithm-faqs.md'
    - 'Apple Health FAQs': 'faqs/apple-health-faqs.md'
    - 'Glossary': 'faqs/glossary.md'
- Translation: 'translate.md'
