site_name: Loop Docs
theme: flatly

pages:
- 'index.md'
- Requirements
    - 'Overview': 'requirements/overview.md'
    - 'Insulin Pump': 'requirements/pump.md'
    - 'CGM': 'requirements/cgm.md'
    - 'RileyLink': 'requirements/rileylink.md'
    - 'Computer': 'requirements/computer.md'
    - 'iPhone': 'requirements/iphone.md'
- Build
    - 'Overview': 'build/overview.md'
    - 'Installing': 'build/installing.md'
    - 'Configuration': 'build/configuration.md'
    - 'Updating': 'build/updating.md'
    - 'Troubleshooting': 'build/troubleshooting.md'
- Use
    - 'Overview': 'use/overview.md'
    - 'Open Loop': 'use/open-loop.md'
    - 'Close Loop': 'use/close-loop.md'
    - 'Green Loop': 'use/green-loop.md'
    - 'Carb Entries': 'use/carbs.md'
    - 'Priming and Sites': 'use/priming.md'
    - 'Time Changes': 'use/time-change.md'
    - 'RileyLink': 'use/rileylink.md'
- Algorithm:
    - 'Overview': 'algorithm/overview.md'
    - 'Glucose Prediction': 'algorithm/prediction.md'
    - 'Temp Basal Adjustments': 'algorithm/temp_basal.md'
    - 'Bolus Recommendations': 'algorithm/bolus.md'
- Nightscout:
    - 'Overview': 'nightscout/overview.md'
    - 'Setup New Site': 'nightscout/new_user.md'
    - 'Update Site': 'nightscout/update_user.md'
    - 'Azure to Heroku': 'nightscout/azure_migration.md'
    - 'mLab': 'nightscout/mlab_cleanup.md'
    - 'Loop Pill': 'nightscout/troubleshooting.md'
    - 'IFTTT': 'nightscout/ifttt.md'
    - 'Remote Notifications': 'nightscout/pushover.md'
    - 'Reports': 'nightscout/reports.md'
