# yaml-language-server: $schema=https://squidfunk.github.io/mkdocs-material/schema.json
site_name: LoopDocs
site_url: https://loopkit.github.io/loopdocs/

theme:
    name: material
    language: en
    features:
        - navigation.footer
        - navigation.tabs
        - navigation.tabs.sticky
        - navigation.tracking
        - navigation.top
        - search.suggest
        - search.highlight
        - content.code.annotate
        - content.tooltips
    logo: loop-logo.png
    favicon: loop-logo.png
    palette:

        # Palette toggle for automatic mode
        - media: "(prefers-color-scheme)"
          toggle:
            icon: material/brightness-auto
            name: Switch to light mode

        # Palette toggle for light mode
        - media: "(prefers-color-scheme: light)"
          scheme: default
          primary: custom
          toggle:
            icon: material/weather-sunny
            name: Switch to dark mode

        # Palette toggle for dark mode
        - media: "(prefers-color-scheme: dark)"
          scheme: slate
          primary: custom
          toggle:
            icon: material/weather-night
            name: Switch to auto (use System Preferences)

# repo_url: https://github.com/LoopKit/Loop

extra_css:
    - stylesheets/primary-color.css
    - stylesheets/extra.css

markdown_extensions:
    - meta
    - abbr
    - admonition
    - attr_list
    - pymdownx.arithmatex:
          generic: true
    - pymdownx.details
    - pymdownx.emoji:
        emoji_index: !!python/name:material.extensions.emoji.twemoji 
        emoji_generator: !!python/name:material.extensions.emoji.to_svg
    - pymdownx.highlight
    - pymdownx.mark
    - pymdownx.tilde
    - pymdownx.inlinehilite
    - pymdownx.keys
    - pymdownx.superfences:
        # make exceptions to highlighting of code:
        custom_fences:
          - name:  mermaid
            class: mermaid
            format: !!python/name:pymdownx.superfences.fence_code_format
    - pymdownx.snippets:
        auto_append:
            - includes/tooltip-list.txt
    - toc:
        permalink: true
        permalink_title: Anchor link to this Header on this Page
        toc_depth: 3
        title: Headers on this Page
extra_javascript:
    - https://cdn.jsdelivr.net/npm/mathjax@3/es5/tex-mml-chtml.js

plugins:
    - open-in-new-tab
    - search
    - htmlproofer:
        enabled: !ENV [CHECK_BROKEN_LINKS, False]
        raise_error_after_finish: true
    - redirects:
        redirect_maps:
            'gh-actions/automatic.md': 'browser/automatic.md'
            'gh-actions/build-dev-browser.md': 'browser/build-dev-browser.md'
            'gh-actions/custom-browser.md': 'browser/custom-browser.md'
            'gh-actions/edit-browser.md': 'browser/edit-browser.md'
            'gh-actions/gh-deploy.md': 'browser/phone-install.md'
            'gh-actions/gh-errors.md': 'browser/bb-errors.md'
            'gh-actions/gh-first-time.md': 'browser/intro-summary.md'
            'gh-actions/gh-other-apps.md': 'browser/other-apps.md'
            'gh-actions/gh-overview.md': 'browser/bb-overview.md'
            'gh-actions/gh-update.md': 'browser/bb-update.md'
            'loop-3/displays_v3.md': 'loop-3/displays-v3.md'
            'nightscout/new_user.md': 'nightscout/new-user.md'
            'nightscout/ns_crossref.md': 'nightscout/ns-crossref.md'
            'nightscout/remote-overrides.md': 'nightscout/remote-overview.md'
            'nightscout/troublehoot.md': 'nightscout/troubleshoot.md'
            'nightscout/update_user.md': 'nightscout/update-user.md'
            'operation/features/workout.md': 'operation/features/overrides.md'
            'troubleshooting/time-change.md': 'faqs/time-faqs.md'
            'troubleshooting/yellow-red-loop.md': 'troubleshooting/red-loop.md'
            'operation/overview.md': 'loop-3/loop-3-overview.md'
            'build/health.md': 'faqs/apple-health-faqs.md'
            'operation/loop-settings/mdt-pump.md': 'loop-3/medtronic.md'
            'operation/loop-settings/omnipod-pump.md': 'loop-3/omnipod.md'
            'operation/loop-settings/cgm.md': 'loop-3/add-cgm.md'
            'operation/loop-settings/configurations.md': 'loop-3/settings.md'
            'operation/loop-settings/services-v2.md': 'loop-3/services.md'
            'operation/loop-settings/displays.md': 'loop-3/displays-v3.md'
            'operation/loop-settings/rileylink.md': 'loop-3/rileylink.md'
            'operation/algorithm/temp-basal.md': 'operation/algorithm/auto-adjust.md'
    - unused_files:
        enabled: !ENV [CHECK_UNUSED_FILES, False]
        excluded_files:
            - .DS_Store
            - loop-logo.png
            - extra.css
            - primary-color.css

use_directory_urls: !ENV [CHECK_BROKEN_LINKS, True]

validation:
    anchors: warn

nav:
- Home: 'index.md'
- Intro:
    - 'LoopDocs Overview': 'intro/overview-intro.md'
    - 'LoopDocs How-to': 'intro/loopdocs-how-to.md'
    - 'Requirements Overview': 'intro/requirements.md'
    - 'Compatible iPhone': 'build/phone.md'
    - 'Compatible Pump': 'build/pump.md'
    - 'Compatible CGM': 'build/cgm.md'
    - 'RileyLink': 'build/rileylink.md'
    - 'Apple Developer Program': 'build/apple-developer.md'
    - 'Test Settings': 'build/test-settings.md'
    - 'Loop Data': 'build/loop-data.md'
    - 'Meet the Community': 'build/community.md'
- Build with Browser:
    - 'Browser Overview': browser/bb-overview.md
    - 'Configure to use Browser':
      - 'Introduction and Summary': browser/intro-summary.md
      - 'Collect Secrets': browser/secrets.md
      - 'Prepare Fork': browser/prepare-fork.md
      - 'Prepare Identifiers': browser/identifiers.md
      - 'Prepare App': browser/prepare-app.md
      - 'Prepare TestFlight Group': browser/tf-users.md
      - 'Create Certificates': browser/certs.md
      - 'Build the App': browser/build-yml.md
    - 'Install on Phone': browser/phone-install.md
    - 'Errors with Browser': browser/bb-errors.md
    - 'Update/Rebuild with Browser': browser/bb-update.md
    - 'Automatic Update & Build': browser/automatic.md
    - 'Customize using Browser': 'browser/custom-browser.md'
    - 'Custom Edits with Browser': 'browser/edit-browser.md'
    - 'Build Loop dev with Browser': browser/build-dev-browser.md
    - 'Build Other Apps with Browser': browser/other-apps.md
- Build with Mac:
    - 'Mac Overview': 'build/overview.md'
    - 'Compatible Computer': 'build/computer.md'
    - 'Xcode Version': 'build/xcode-version.md'
    - 'Xcode Settings': 'build/xcode-settings.md'
    - 'Build Loop': 'build/build-app.md'
    - 'Oh dear! Build errors?': 'build/build-errors.md'
    - 'Update/Rebuild with Mac': 'build/updating.md'
    - 'Customize using Mac': 'build/custom-mac.md'
    - 'Custom Edits with Mac': 'build/edit-mac.md'
    - 'Build Loop dev with Mac': 'build/build-dev-mac.md'
    - 'Build Free Loop': 'build/build-free-loop.md'
    - 'TestFlight from Xcode': 'build/testflight-xcode.md'
- Set Up:
    - 'Overview': 'loop-3/loop-3-overview.md'
    - 'Onboarding': 'loop-3/onboarding.md'
    - 'Add CGM': 'loop-3/add-cgm.md'
    - 'Add Pump': 'loop-3/add-pump.md'
    - 'Settings': loop-3/settings.md
    - 'Therapy Settings': 'loop-3/therapy-settings.md'
    - 'Optional: Services': 'loop-3/services.md'
    - 'Displays': 'loop-3/displays-v3.md'
    - 'RileyLink Display': 'loop-3/rileylink.md'
    - 'Omnipod Pump': loop-3/omnipod.md
    - 'Medtronic Pump': loop-3/medtronic.md
    - 'Features': 'loop-3/features.md'
- Operate:
    - 'Open Loop': 'operation/loop/open-loop.md'
    - 'Closed Loop': 'operation/loop/close-loop.md'
    - 'Meal Entries': 'operation/features/carbs.md'
    - 'Bolus': 'operation/features/bolus.md'
    - 'Overrides': 'operation/features/overrides.md'
    - 'Apple Watch': 'operation/features/watch.md'
    - 'Loop Notifications': 'operation/features/notifications.md'
    - 'Pre-Meal Target': 'operation/features/premeal.md'
    - 'Meal Review': 'operation/features/ice.md'
    - 'iPhone Widget': 'operation/features/widget.md'
    - Loop Tips: 'operation/loop/looptips.md'
    - Algorithm:
        - 'Algorithm Overview': 'operation/algorithm/overview.md'
        - 'Bolus Recommendations': 'operation/algorithm/bolus.md'
        - 'Glucose Prediction': 'operation/algorithm/prediction.md'
        - 'Automated Adjustments': 'operation/algorithm/auto-adjust.md'
- Troubleshoot:
    - 'Troubleshooting Overview': 'troubleshooting/overview.md'
    - 'Loop App Crashes': 'troubleshooting/loop-crashing.md'
    - 'Red Loop': 'troubleshooting/red-loop.md'
    - 'Pod Pairing Failures': 'troubleshooting/pod-pairing.md'
    - 'Omnipod Faults': 'troubleshooting/omnipod-faults.md'
    - 'MDT Pump Errors': 'troubleshooting/pump-errors.md'
    - 'MDT Pump Battery': 'operation/features/battery.md'
    - 'Dana (RS/-i) FAQ': 'troubleshooting/dana-faq.md'
- 'Version':
    - 'Version Overview': 'version/overview-version.md'
    - 'Releases': 'version/releases.md'
    - 'Custom Edits': 'version/code-custom-edits.md'
    - 'Build-Time Flag': 'version/build-time-flag.md'
    - 'Simulator Build': 'version/simulator.md'
    - 'Loop Development': 'version/development.md'
    - 'Build Dev': 'version/build-dev.md'
    - 'LoopWorkspace': 'version/loopworkspace.md'
    - 'Older Releases':
      - 'Loop 2 and Older': version/releases-version2.md
- Nightscout:
    - 'Nightscout Overview': 'nightscout/overview.md'
    - 'New Nightscout': 'nightscout/new-user.md'
    - 'Nightscout with Loop': 'nightscout/update-user.md'
    - 'Nightscout Troubleshooting': 'nightscout/troubleshoot.md'
    - 'Nightscout Cross Ref': 'nightscout/ns-crossref.md'
    - 'Remote Overview': 'nightscout/remote-overview.md'
    - 'Remote Configuration': 'nightscout/remote-config.md'
    - 'Remote Commands': 'nightscout/remote-commands.md'
    - 'Remote Errors': 'nightscout/remote-errors.md'
    - '<span translate="no">LoopCaregiver<span>': 'nightscout/loop-caregiver.md'
- FAQs:
    - 'FAQs Overview': 'faqs/overview-faqs.md'
    - 'Safety Tips': 'faqs/safety-faqs.md'
    - 'Loop FAQs': 'faqs/loop-faqs.md'
    - 'Time FAQs': 'faqs/time-faqs.md'
    - 'Omnipod FAQs': 'faqs/omnipod-faqs.md'
    - 'CGM FAQs': 'faqs/cgm-faqs.md'
    - 'Update/Rebuild Loop FAQs': 'faqs/update-faqs.md'
    - 'New Phone Tips': 'faqs/new-phone.md'
    - 'Remote Control FAQs': 'faqs/remote-control.md'
    - 'Translation FAQS': 'faqs/app-translation'
    - 'Algorithm FAQs': 'faqs/algorithm-faqs.md'
    - 'Apple Health FAQs': 'faqs/apple-health-faqs.md'
    - 'RileyLink FAQs': 'faqs/rileylink-faqs.md'
    - 'Glossary': 'faqs/glossary.md'
- Translation: 'translate.md'
