site_name: LoopDocs
theme: flatly
google_analytics: ['UA-109876065-1', 'loopkit.github.io']
extra_css:
    - css/admonitions.css
markdown_extensions:
    - admonition
    - toc:
        permalink: ‚åÅ

pages:
- Home: 'index.md'
- FAQs:
    - 'Using This Site FAQs': 'faqs/docs-faqs.md'
    - 'General Loop FAQs': 'faqs/FAQs.md'
    - 'Omnipod FAQs': 'faqs/omnipod-faqs.md'
    - 'Branch FAQs': 'faqs/branch-faqs.md'
    - 'Update/Rebuild Loop FAQs': 'faqs/update-faqs.md'
    - 'iOS 13 FAQs': 'faqs/ios13.md'
    - 'RileyLink FAQs': 'faqs/rileylink-faqs.md'
    - 'Algorithm FAQs': 'faqs/algorithm-faqs.md'
    - 'CGM FAQs': 'faqs/cgm-faqs.md'
    - 'Safety Tips': 'faqs/safety-faqs.md'
- Build App:
    - Overview: 'build/overview.md'
    - 'Step 1 Compatible Computer': 'build/step1.md'
    - 'Step 2 Compatible iPhone/iPod touch': 'build/step2.md'
    - 'Step 3 Compatible Pump': 'build/step3.md'
    - 'Step 4 Compatible CGM': 'build/step4.md'
    - 'Step 5 Order a RileyLink': 'build/step5.md'
    - 'Step 6 Enroll in Apple Developer Program': 'build/step6.md'
    - 'Step 7 Install Homebrew': 'build/step7.md'
    - 'Step 8 Download Xcode': 'build/step8.md'
    - 'Step 9 Xcode Preferences': 'build/step9.md'
    - 'Step 10 Test Settings': 'build/step10.md'
    - 'Step 11 Make plans for Loop Data': 'build/step11.md'
    - 'Step 12 Meet Community': 'build/step12.md'
    - 'Step 13 Download Loop code': 'build/step13.md'
    - 'Step 14 Build Loop app': 'build/step14.md'
    - 'Oh dear! Build errors?': 'build/build_errors.md'
    - 'Customize your Loop': 'build/code_customization.md'
    - 'Updating/Rebuilding your Loop': 'build/updating.md'
    - 'LoopWorkspace': 'build/loopworkspace.md'
- Set up App:
    - 'Overview': 'operation/overview.md'
    - 'Step 1: Health Permissions': 'build/health.md'
    - 'Step 2: Add Pump':
        - 'Add Medtronic': 'operation/loop-settings/mdt-pump.md'
        - 'Add Omnipod': 'operation/loop-settings/omnipod-pump.md'
    - 'Step 3: Add CGM': 'operation/loop-settings/cgm.md'
    - 'Step 4: Configurations': 'operation/loop-settings/configurations.md'
    - 'Step 5: Loop Services': 'operation/loop-settings/services.md'
    - 'Loop Displays': 'operation/loop-settings/displays.md'
    - 'RileyLink menu': 'operation/loop-settings/rileylink.md'
- Operate:
    - How to Use Loop App:
        - 'Carb Entries': 'operation/features/carbs.md'
        - 'Bolus': 'operation/features/bolus.md'
        - 'Overrides': 'operation/features/workout.md'
        - 'Pre-meal target': 'operation/features/premeal.md'
        - 'Health app': 'operation/features/healthapp.md'
        - 'Using ICE info': 'operation/features/ice.md'
        - 'Apple Watch': 'operation/features/watch.md'
        - 'iPhone widget': 'operation/features/widget.md'
        - 'Loop Notifications': 'operation/features/notifications.md'
        - 'Pump Battery': 'operation/features/battery.md'
    - Looping Tips:
        - 'Open Loop': 'operation/loop/open-loop.md'
        - 'Closed Loop': 'operation/loop/close-loop.md'
        - 'Loop Tips': 'operation/loop/looptips.md'
    - Algorithm:
        - 'Overview': 'operation/algorithm/overview.md'
        - 'Bolus Recommendations': 'operation/algorithm/bolus.md'
        - 'Glucose Prediction': 'operation/algorithm/prediction.md'
        - 'Temp Basal Adjustments': 'operation/algorithm/temp-basal.md'
    - Troubleshoot:
        - 'Overview': 'troubleshooting/overview.md'
        - 'Loop App crashes': 'troubleshooting/loop-crashing.md'
        - 'Red Loop': 'troubleshooting/yellow-red-loop.md'
        - 'Pod Pairing Failures': 'troubleshooting/pod-pairing.md'
        - 'Pod Uncertain Boluses': 'troubleshooting/uncertain-bolus.md'
        - 'MDT Priming and Sites': 'troubleshooting/priming.md'
        - 'Time Changes': 'troubleshooting/time-change.md'
        - 'MDT Pump Errors': 'troubleshooting/pump-errors.md'
        - 'Omnipod Faults': 'troubleshooting/omnipod-faults.md'
- Nightscout:
    - 'Overview': 'nightscout/overview.md'
    - 'Brand New NS': 'nightscout/new_user.md'
    - 'Retrofit Existing NS': 'nightscout/update_user.md'
    - 'Setup Troubleshooting': 'nightscout/troublehoot.md'
    - 'NS Stopped Working': 'nightscout/mlab_cleanup.md'
    - 'Remote Overrides': 'nightscout/remote-overrides.md'
    - 'IFTTT': 'nightscout/ifttt.md'
    - 'Pebble': 'nightscout/pebble.md'
    - 'Remote Notifications': 'nightscout/pushover.md'
    - 'Reports': 'nightscout/reports.md'
