name: publish

# Controls when the action will run.
on:
  # Remark: uncomment one section only
  # Remark: Next 1 line requires manual action, Click on action tab, then publish
  # workflow_dispatch
  # Remark: Next 3 lines triggers the workflow on push events for the main branch
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest
    permissions:
      contents: write
    if: github.repository_owner == 'LoopKit'
    steps:
      - uses: actions/checkout@v5
      - uses: actions/setup-python@v6
        with:
          python-version: ">=3.9"
      - run: pip install -r requirements.txt
      - run: mkdocs build

      - uses: JamesIves/github-pages-deploy-action@v4
        with:
          branch: gh-pages
          folder: site
